package com.models.questions;

public enum QuestionType {
	QuestionResponse {
		public String toString() {
			return "question-response";
		}
	},
	FillInTheBlank {
		public String toString() {
			return "fill-in-the-blank";
		}
	},
	MultiAnswer {
		public String toString(){
			return "multi-answer";
		}
	},
	PictureResponse{
		public String toString(){
			return "picture-response";
		}
	},
	MultiChoice{
		public String toString(){
			return "multiple-choice";
		}
	},
	MultiChoiceMultiAnswer{
		public String toString(){
			return "multiple-choice-multiple-answer";
		}
	},
	Matching{
		public String toString(){
			return "matching";
		}
	},
	AutoGenerated {
		public String toString(){
			return "auto-generated";
		}
	},
	Graded {
		public String toString(){
			return "graded";
		}
	}
}
